Fix: AI drivers now works.
Global-Conflicts-ArmA/Olsen-Framework-Arma-3 pull request #46
Opened 2021-04-05 14:07 UTC by EM-Creations

**When merged this pull request will:**
- Fix the AI drivers module

Reported by @goosko bug #37.

The list of specific vehicles to add driver AI on wasn't being used, also because there was no wait until the vehicles were even created in the game none of the other options would work.

2021-04-06 19:04 UTC, EM-Creations commented on modules/ai_drivers/settings.sqf
>  // Array containing vehicles that will have option to spawn AI driver in them
This file is effectively unmodified, just showing up as having made changes for some reason..

2021-04-06 19:23 UTC, PiZZAD0X requested changes
Do we need the waituntilandexecute? What about just a postInit? All vehicles should be loaded in the postInit (past briefing)

2021-04-07 17:09 UTC, EM-Creations commented
> Do we need the waituntilandexecute? What about just a postInit? All vehicles should be loaded in the postInit (past briefing)

You're right, it wasn't necessarily, call to init the module now moved to a post init XEH.

2021-04-08 20:15 UTC, PiZZAD0X approved these changes

2021-04-09 16:23 UTC, merged