Vehicle boost module
Global-Conflicts-ArmA/Olsen-Framework-Arma-3 pull request #62
Opened 2021-05-23 11:17 UTC by EM-Creations

**When merged this pull request will:**
- Add a new "Vehicle Boost" module to the framework which allows mission makers to specify specific vehicles as having a "BOOST" option set to their desired speed increase and cooldown.

2021-08-11 00:17 UTC, PiZZAD0X requested changes
Good module addition, just needs the CBA time and it is good to go

2021-08-11 00:17 UTC, PiZZAD0X commented on modules/vehicle_boost/functions/VEHBOOST/fn_VEHBOOST_Boost.sqf
> +if ((GVAR(boostLastUsed) + GVAR(vehicleBoostDelay)) > time) exitWith {};
use `CBA_MissionTime` instead of `time`
```suggestion
if ((GVAR(boostLastUsed) + GVAR(vehicleBoostDelay)) > CBA_MissionTime) exitWith {};
```

2021-08-11 00:17 UTC, PiZZAD0X commented on modules/vehicle_boost/functions/VEHBOOST/fn_VEHBOOST_Boost.sqf
> +GVAR(boostLastUsed) = time;
```suggestion
GVAR(boostLastUsed) = CBA_MissionTime;
```

2021-08-11 00:17 UTC, PiZZAD0X commented on modules/vehicle_boost/postInitClient.sqf
> +	[{time > 0}, {
```suggestion
	[{CBA_MissionTime> 0}, {
```

2021-08-11 16:04 UTC, EM-Creations commented
Fixes made.

2021-08-13 18:03 UTC, PiZZAD0X approved these changes

2021-08-14 07:45 UTC, merged